---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jvuojbwk/handyman.r00tex910it.com
    - /bin/cp -R ./* $DEPLOYPATH/
    - /bin/cp ./.env $DEPLOYPATH/.env
    - cd $DEPLOYPATH
    - /usr/local/bin/composer install --no-dev --optimize-autoloader
    - /usr/local/bin/php artisan migrate
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - /usr/local/bin/php artisan storage:link
    - /bin/chown -R jvuojbwk:jvuojbwk $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache
    - /bin/chmod -R 775 $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache
