on:
  push:
    branches:
      - production  # Change this to your deployment branch

  pull_request:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add GitHub to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Install SSH Client
      run: sudo apt-get install -y ssh

    - name: Debug SSH Setup
      run: |
        echo "Host: ${{ secrets.HOST }}"
        echo "Username: ${{ secrets.USERNAME }}"
        echo "Port: ${{ secrets.PORT }}"

    - name: Verbose SSH Output
      run: |
        set -x  # Enable debugging
        ssh -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} exit

    - name: Setup SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /repositories  # Change to your application directory on the server
          git pull origin production
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
